[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
viaIR = true
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
]
solc_version = "0.8.22"

[rpc_endpoints]
88882 = "${CHILIZ_RPC_URL}"

